import potImg1 from "../test/plant1.png";
import potImg2 from "../test/plant2.png";
import kidImg1 from "../test/kid1.png";
import kidImg2 from "../test/kid2.png";

export const NEW_TALK_LIST = [
  {
    talkID: 1,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg1,
    potImg: potImg1,
    isRead: false,
    isFavorite: false,
  },
  {
    talkID: 2,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg2,
    potImg: potImg2,
    isRead: false,
    isFavorite: false,
  },
];

export const TALK_LIST = [
  {
    talkID: 1,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg1,
    potImg: potImg1,
    isRead: false,
    isFavorite: false,
  },
  {
    talkID: 2,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg1,
    potImg: potImg1,
    isRead: true,
    isFavorite: true,
  },
  {
    talkID: 3,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg2,
    potImg: potImg2,
    isRead: false,
    isFavorite: false,
  },
  {
    talkID: 4,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg2,
    potImg: potImg2,
    isRead: true,
    isFavorite: true,
  },
  {
    talkID: 5,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg1,
    potImg: potImg1,
    isRead: false,
    isFavorite: false,
  },
  {
    talkID: 6,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg1,
    potImg: potImg1,
    isRead: true,
    isFavorite: true,
  },
  {
    talkID: 7,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg2,
    potImg: potImg2,
    isRead: false,
    isFavorite: false,
  },
  {
    talkID: 8,
    created_DT: "2024-02-04 18:44",
    talkTitle: "2월4일18시의 대화",
    userImg: kidImg2,
    potImg: potImg2,
    isRead: true,
    isFavorite: true,
  },
];
export const TALK_DETAIL = {
  talkID: 1,
  created_DT: "2024-02-04 18:44",
  talkTitle: "2월4일18시의 대화",
  userImg: kidImg1,
  userName: "성주",
  potImg: potImg1,
  isFavorite: false,
  sentence: [
    {
      id: 1,
      talker: "kid",
      content: "오늘 점심에 볶음밥이 너무 맛있었어",
      file: "audio",
    },
    {
      id: 2,
      talker: "gpt",
      content: "와, 볶음밥 좋지! 뭐 들어갔어? 다음엔 같이 먹어보자!",
      file: "audio",
    },
    {
      id: 3,
      talker: "kid",
      content: "두그릇 먹고싶었는데 못먹어서 아쉬워",
      file: "audio",
    },
    {
      id: 4,
      talker: "gpt",
      content: "다음엔 두 그릇 먹어봐!",
      file: "audio",
    },
    {
      id: 5,
      talker: "kid",
      content: "오늘 점심에 볶음밥이 너무 맛있었어",
      file: "audio",
    },
    {
      id: 6,
      talker: "gpt",
      content: "와, 볶음밥 좋지! 뭐 들어갔어? 다음엔 같이 먹어보자!",
      file: "audio",
    },
    {
      id: 7,
      talker: "kid",
      content: "두그릇 먹고싶었는데 못먹어서 아쉬워",
      file: "audio",
    },
    {
      id: 8,
      talker: "gpt",
      content: "다음엔 두 그릇 먹어봐!",
      file: "audio",
    },
    {
      id: 9,
      talker: "kid",
      content: "오늘 점심에 볶음밥이 너무 맛있었어",
      file: "audio",
    },
    {
      id: 10,
      talker: "gpt",
      content: "와, 볶음밥 좋지! 뭐 들어갔어? 다음엔 같이 먹어보자!",
      file: "audio",
    },
    {
      id: 11,
      talker: "kid",
      content: "두그릇 먹고싶었는데 못먹어서 아쉬워",
      file: "audio",
    },
    {
      id: 12,
      talker: "gpt",
      content: "다음엔 두 그릇 먹어봐!",
      file: "audio",
    },
  ],
};
